### ISSUE TITLE
AllowBackup in AndroidManifest conflicts with actual apps configuration

### ISSUE THREAD

**Issue by ryanzor** [cedexis/AndroidRadar#14]
I don't think there is any reason to have that in the androidManifest.xml

**Comment by jmsalcido** [comment]
hi @ryanzor there is no reason to have that in the AndroidManifest.xml seems to be from old releases, for the next release I'll remove it.

**Comment by jmsalcido** [comment]
this is fixed in 0.2.0 https://github.com/cedexis/AndroidRadar/releases/tag/v0.2.0
