### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by manuel-sejourne** [cedexis/AndroidRadar#16]
Hi 

I notice a issue when using your sdk:

Crashed Thread
0	java.lang.NullPointerException: Attempt to get length of null array
!	1	at com.cedexis.androidradar.d.d(d.java:83)
2	at com.cedexis.androidradar.e.j(e.java:333)
3	at com.cedexis.androidradar.RadarService.onHandleIntent(RadarService.java:25)
4	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
5	at android.os.Handler.dispatchMessage(Handler.java:102)
6	at android.os.Looper.loop(Looper.java:150)
7	at android.os.HandlerThread.run(HandlerThread.java:61)

Could you correct this ?

**Comment by manuel-sejourne** [comment]
I am in 0.1.6 Maybe the last version will correct it ?

**Comment by ronylerner** [comment]
Hi Manuel, thanks for taking the time to comment. The issue above should be solve in the latest version.
