### ISSUE TITLE
java.lang.IllegalStateException This API not supported on Android 4.3 and earlier

### ISSUE THREAD

**Issue by manuel-sejourne** [cedexis/AndroidRadar#17]
Hi,

I have a crash in production: 
This API not supported on Android 4.3 and earlier
java.lang.IllegalStateException

Crashed Thread

0	java.lang.IllegalStateException: This API not supported on Android 4.3 and earlier
1	at android.webkit.WebViewClassic.evaluateJavaScript(WebViewClassic.java:2674)
2	at android.webkit.WebView.evaluateJavascript(WebView.java:905)
!	3	at com.cedexis.androidradar.b.onPageFinished(b.java:46)
4	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:324)
5	at android.os.Handler.dispatchMessage(Handler.java:102)
6	at android.os.Looper.loop(Looper.java:136)
7	at android.app.ActivityThread.main(ActivityThread.java:5001)
8	at java.lang.reflect.Method.invokeNative(Method.java)
9	at java.lang.reflect.Method.invoke(Method.java:515)
10	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
11	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
12	at dalvik.system.NativeStart.main(NativeStart.java)

Can you correct this ?

Thank you

**Comment by manuel-sejourne** [comment]
Update

**Comment by jmsalcido** [comment]
Hi @manuel-sejourne seems to be a problem with a custom rom.
https://groups.google.com/forum/#!topic/ima-sdk/_jlq5qAmqRQ

I'll do more research and help you with that!

**Comment by jakewan** [comment]
This should be fixed in the latest release:

https://github.com/cedexis/AndroidRadar/releases/tag/v0.2.6
