### ISSUE TITLE
Bintray sunsetting on May 1

### ISSUE THREAD

**Issue by shashachu** [cedexis/AndroidRadar#27]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Is this library going to be hosted anywhere else?

**Comment by aristotelism** [comment]
@shashachu  This is in progress...

**Comment by shashachu** [comment]
Thank you!

**Comment by aristotelism** [comment]
Hi @shashachu. I have released a new version of the library in jitpack. The library itself does not not have any actual changes. Please let me know if you have any issues/questions.

**Comment by shashachu** [comment]
Looks like it's working for us. Thanks!
