### ISSUE TITLE
JavaScript error "cedexis undefined"

### ISSUE THREAD

**Issue by etanmtv** [cedexis/AndroidRadar#31]
The following error is logged by the WebView:

[INFO:CONSOLE(1)] "Uncaught ReferenceError: cedexis is not defined", source: chrome-error://chromewebdata/ (1)

EDIT: This happens when cleartext traffic to cedexis URLs is not permitted, the error could be more descriptive.

**Comment by chris7ceid** [comment]
Hi, in your code cedexis.start looks like this?
```
cedexis.start(zoneId, customerId, RadarScheme.HTTPS);
```

**Comment by etanmtv** [comment]
Yes I realised that HTTP traffic was the issue. The error could be a little more descriptive though :)
