### ISSUE TITLE
Crash on RadarService.onDestroy() method

### ISSUE THREAD

**Issue by mrbipbip** [cedexis/AndroidRadar#8]
Hi!

I got this crash after a long period without using my device:

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.cedexis.androidradar.RadarSession.stop()' on a null object reference
at com.cedexis.androidradar.RadarService.onDestroy(RadarService.java:32)
at android.app.ActivityThread.handleStopService(ActivityThread.java:2954)`

The RadarSession object seems to be null (garbaged) on the RadarService class.
Can you add a simple verification of the RadarSession object before to call the stop() method?

Thanks a lot !
Have a good day !

Alexis.

**Comment by jakewan** [comment]
Alexis, thanks for the report.  We'll be publishing a version with Javier's fix to jCenter and Maven Central later today.

**Comment by mrbipbip** [comment]
Thanks for your reactivity.
